### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by csells** [hediet/vscode-debug-visualizer#86]
This visualizer would go great with Flutter!

**Comment by hediet** [comment]
I haven't worked with dart yet, but I'm open for contributions and can offer assistance ;)

If the dart debug adapter for VS Code prints strings properly, JSON strings can already be visualized when debugging dart apps in VS Code!

**Comment by csells** [comment]
@dantup might be interested in helping here

**Comment by DanTup** [comment]
I did some testing of this last week and was able to get some renderings working by creating a helper function and just calling it in the evaluation window (which I think is what many of the other language demos are doing here?).

![unnamed](https://user-images.githubusercontent.com/1078012/93664912-4f2c4480-fa6a-11ea-8ddf-462b6e64e93c.gif)

It could be useful to commit a demo here that has helpers like this for each type of supported visualisation that people can copy/tweak to suit their project?

**Comment by hediet** [comment]
> I did some testing of this last week and was able to get some renderings working by creating a helper function and just calling it in the evaluation window 

Nice!

There is also the concept of "Data Extractors" (soon to be renamed to "Visualization Brokers"). In case of javascript, they are injected into the debuggee and translate some common data structures into json visualization data!
It would be awesome to have data extractors for dart so that int-arrays or object-arrays or objects with a "getVisualizationData()" method are visualized automatically.

If multiple data extractors can produce some visualization data for a given value, the user can select one of them.

Anyways, I'd be very happy if you could open a PR with your dart demos ;) They are a great starting point!
